services:
  # -----
  # gluetun VPN
  # -----

  gluetun:
    image: qmcgaw/gluetun:3.41.3
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8090:8090 # qbittorrent webUI
      - 9696:9696 # prowlarr webUI
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_CITIES=${SERVER_CITIES}
      - TZ=${TZ}
      - FIREWALL=on # VPN kill switch
      - FIREWALL_INPUT_PORTS=8090,9696
      - VPN_PORT_FORWARDING=on
      - PORT_FORWARD_ONLY=on
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c 'wget -O- -nv --retry-connrefused --post-data "json={\"listen_port\":{{PORT}},\"current_network_interface\":\"{{VPN_INTERFACE}}\",\"random_port\":false,\"upnp\":false}" http://10.10.20.31:8090/api/v2/app/setPreferences'
      - VPN_PORT_FORWARDING_DOWN_COMMAND=/bin/sh -c 'wget -O- -nv --retry-connrefused --post-data "json={\"listen_port\":0,\"current_network_interface\":\"lo\"}" http://10.10.20.31:8090/api/v2/app/setPreferences'
    volumes:
      - /opt/docker/mediarr/config/gluetun:/gluetun
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "https://ipinfo.io"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    
  # -----
  # qbittorrent
  # -----

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:5.2.3
    container_name: qbittorrent
    network_mode: service:gluetun
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8090
    volumes:
      - /opt/docker/mediarr/config/qbittorrent:/config
      - /mnt/media/downloads:/data
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

  # -----
  # byparr
  # -----

  byparr:
    image: ghcr.io/thephaseless/byparr:latest
    container_name: byparr
    security_opt:
      - no-new-privileges:true
    ports:
      - 8191:8191
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=${TZ}
    restart: unless-stopped

  # -----
  # prowlarr
  # -----

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.5.2.5491
    container_name: prowlarr
    network_mode: service:gluetun
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /opt/docker/mediarr/config/prowlarr:/config
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

  # -----
  # radarr
  # -----
    
  radarr:
    image: lscr.io/linuxserver/radarr:6.3.0.10514
    container_name: radarr
    ports:
      - 7878:7878
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /opt/docker/mediarr/config/radarr:/config
      - /mnt/media/downloads:/data
    restart: unless-stopped

  # -----
  # sonarr
  # -----
  
  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.19.2979
    container_name: sonarr
    ports:
      - 8989:8989
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /opt/docker/mediarr/config/sonarr:/config
      - /mnt/media/downloads:/data
    restart: unless-stopped

  # -----
  # recyclarr
  # -----

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:8
    container_name: recyclarr
    user: ${PUID}:${PGID}
    environment:
      - RECYCLARR_CREATE_CONFIG=true
      - TZ=${TZ}
    volumes:
      - /opt/docker/mediarr/config/recyclarr:/config
    restart: unless-stopped

  # -----
  # bazaarr
  # -----
  
  bazarr:
    image: lscr.io/linuxserver/bazarr:1.6.0
    container_name: bazarr
    ports:
      - 6767:6767
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /opt/docker/mediarr/config/bazarr:/config
      - /mnt/media/downloads/:/data
    depends_on:
      - radarr
      - sonarr
    restart: unless-stopped

  # -----
  # seerr
  # -----
  
  seerr:
    image: ghcr.io/hotio/seerr:3.4.1
    container_name: seerr
    ports:
      - 5055:5055
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /opt/docker/mediarr/config/seerr:/config
    depends_on:
      - radarr
      - sonarr
    restart: unless-stopped